// SPDX-License-Identifier: Apache-2.0
// Generated by rustemo (build.rs) — clippy findings there are the
// generator's, not ours; a regeneration would erase hand-fixes.
#[allow(clippy::all)]
pub mod cola;
#[allow(clippy::all)]
pub mod cola_actions;
